### ISSUE TITLE
Make definitions library available to LLS

### ISSUE THREAD

**Issue by luttje** [luttje/glua-api-snippets#1]
Consider making this a VSCode Extension as mentioned here:

> Additionally this could be made into a vscode extension which automatically injects it into sumneko's lua:
> https://github.com/sumneko/lua-language-server/wiki/EmmyLua-Libraries
> 
> _Originally posted by @Vurv78 in https://github.com/Lexicality/libgmod/issues/3#issuecomment-1007054909_

**Comment by Vurv78** [comment]
Would be very much appreciated

**Comment by luttje** [comment]
> Would be very much appreciated,
> 
> Also fyi probably want to recommend lua language server instead of the old emmylua extension in your readme, even if the annotations are not 1:1 they mostly add onto it rather than change it, so you could keep the annotations functional across editors.

Heya, thanks for the heads-up! I'll make an issue for it so I don't forget.

**Comment by luttje** [comment]
When this PR is merged: https://github.com/LuaLS/LLS-Addons/pull/49 I will:

- [ ] Update readme to add installation instructions (using Lua Language Server Addon manager)
- [ ] Add note to readme pointing out how to contribute. Especially instructions so anyone can help update the subrepo at LLS-Addons
- [ ] Close this issue
