### ISSUE TITLE
Optional parameters

### ISSUE THREAD

**Issue by Vurv78** [luttje/glua-api-snippets#10]
Parameters with default values (ie `Color(r, g, b, a = 255)`) ignore the default values, leading to warnings with editors that enforce correct number of parameters to call a function (LuaLS, IntelliJ probably also makes this a warning)

**Comment by luttje** [comment]
Thanks for taking your time to contribute in this way. I greatly appreciate it!

I've got an idea where to implement this. Luckily the wiki has consistent formatting for this (from what I've seen). Sadly I'll implement parameters like this as [optional

I'll do that later this week
