### ISSUE TITLE
Need some fixes

### ISSUE THREAD

**Issue by AMD-NICK** [luttje/glua-api-snippets#13]
`timer.Adjust`
<img width="546" alt="screenshot_2023-07-20_06 00 43@2x" src="https://github.com/luttje/glua-api-snippets/assets/9200174/a180308d-9c9a-407d-b7d6-b995aafa529a">
all parameters are optional

`GAMEMODE.FolderName`
![screenshot_2023-07-20_06 03 13@2x](https://github.com/luttje/glua-api-snippets/assets/9200174/86a09f87-9fb9-4bfe-aef2-0895f5612ca0)
https://wiki.facepunch.com/gmod/~search:FolderName

**Comment by luttje** [comment]
Hi @AMD-NICK, thanks for reporting this!

The first problem (timer.Adjust) needs to be fixed on the wiki itself. The optional args need a default provided. Like with this function (go to edit on the wiki to see the syntax): https://wiki.facepunch.com/gmod/cam.PushModelMatrix

The second is indeed something the scraper currently does not pick up on. I may look into this in a couple months or I'll accept a PR that implements a fix as well.

**Comment by Vurv78** [comment]
I've edited the wiki entry for `timer.Adjust` to have defaults set for the last two arguments

**Comment by luttje** [comment]
@all-contributors please add @AMD-NICK for bug
