### ISSUE TITLE
Define node compatibility

### ISSUE THREAD

**Issue by aske02** [luttje/glua-api-snippets#14]
Node compatibility should be defined in [package.json](package.json) due to [scraper.ts](./scr/scrapers/scraper.ts) using a node >18.0.0 feature  `global.fetch`.
As node 16.x is still used by some people, it could create confusion.
Due to the error not being so detailed when global.fetch is not defined.
The error:
```
ArgumentError {
  name: 'ArgumentError',
  message: 'fetch must be a function'
}
```

The suggestion is to add the following to the [package.json](package.json)
```json
"engines": {
	"node": ">=18.0.0"
  },
"engineStrict": true
  ````

**Comment by luttje** [comment]
Hey @aske02, thanks for this report! You are very much right that this confusion should be prevented by the fix you suggest.

Sadly I don't have time to update, but if you can make a PR I'll be happy to merge. Otherwise I'll have a look in a month or so.

Thanks

**Comment by aske02** [comment]
Sure ill make a PR.
The issue `global.fetch` was an experimental feature in node 16.x which was disabled by default and enabled with `--experimental-fetch`.
In node 18.x its still an experimental feature but should be disabled by the user with `--no-experimental-fetch`.
[The pull request for global.fetch](https://github.com/nodejs/node/pull/41811)
