### ISSUE TITLE
Malformed return tags

### ISSUE THREAD

**Issue by aske02** [luttje/glua-api-snippets#19]
Seems like most functions that return more than one argument has its `@return` tag generated more than once.
![](https://i.imgur.com/XcFb1WP.png)
```lua
---[SHARED AND MENU] If the result of the first argument is false or nil, an error is thrown with the second argument as the message.
---
---[(View on wiki)](https://wiki.facepunch.com/gmod/Global.assert)
---@param expression any The expression to assert.
---@param errorMessage? string The error message to throw when assertion fails. This is only type-checked if the assertion fails.
---@param ...? ... Any arguments past the error message will be returned by a successful assert.
---@return any, any, ... #any - If successful, returns the first argument.
---@return any, any, ... #any - If successful, returns the error message. This will be nil if the second argument wasn't specified.  Since the second argument is only type-checked if the assertion fails, this doesn't have to be a string.
---@return any, any, ... #... - Returns any arguments past the error message.
function _G.assert(expression, errorMessage, ...) end
```

**Comment by luttje** [comment]
IIRC this wasn't a problem for the hints in vscode. They seemed to work fine for me and show all information.

If they are problematic let me know and I'll pick this up for you in a couple weeks.

**Comment by aske02** [comment]
It does seem to create some invalid return values, an example is `concommand.GetTable()` which according to the wiki returns 2 tables. But in this context returns 4 tables.
![l4ol4pb](https://github.com/luttje/glua-api-snippets/assets/45128441/92a9ef4b-cf20-479e-b52f-570755ac0100)

All 4 return values are also types as being tables, which is invalid.
![](https://github.com/luttje/glua-api-snippets/assets/45128441/73985c66-7631-46f9-b9a1-b235604bf576)
![](https://github.com/luttje/glua-api-snippets/assets/45128441/7c5d8edb-3af1-4ce3-a190-af7394965cd1)

It currently is generated to look like this:
```lua
---[SHARED AND MENU] Returns the tables of all console command callbacks, and autocomplete functions, that were added to the game with concommand.Add.
---
---[(View on wiki)](https://wiki.facepunch.com/gmod/concommand.GetTable)
---@return table, table #table - Table of command callback functions.
---@return table, table #table - Table of command autocomplete functions.
function concommand.GetTable() end
```

**But should be**
```lua
---[SHARED AND MENU] Returns the tables of all console command callbacks, and autocomplete functions, that were added to the game with concommand.Add.
---
---[(View on wiki)](https://wiki.facepunch.com/gmod/concommand.GetTable)
---@return table # Table of command callback functions.
---@return table # Table of command autocomplete functions.
function concommand.GetTable() end
```

**Comment by luttje** [comment]
Thanks for correcting me, that does indeed seem problematic. I'll pick that up in a couple weeks.

**Comment by Vurv78** [comment]
Unrelated to this, but I feel like nothing should be generated for these standard library functions which are already documented by LuaLS.

You get generics and a more in-depth description of them with LuaLS anyway.

**Comment by luttje** [comment]
@Vurv78 Good point you've got there. I'll extract it to a separate issue so we can track it.
