### ISSUE TITLE
CreateConVar signature wrong

### ISSUE THREAD

**Issue by EntranceJew** [luttje/glua-api-snippets#24]
it thinks "helptext" is necessary, but it comes after a parameter with a nil default

**Comment by luttje** [comment]
Hey there, thanks for reporting this. However this is something that's incorrectly documented on the wiki and thus should be fixed there: https://wiki.facepunch.com/gmod/Global.CreateConVar

**Comment by Vurv78** [comment]
It seems to work fine without any errors for me when only passing the first two arguments? Maybe this was recently fixed or changed?

Unless you meant that helptext wasn't documented properly, I do see that rubat recently made some changes to helptext default, but all he did was change from `default=""` to `default=" "` and then back to `default=""`..?

https://wiki.facepunch.com/gmod/Global.CreateConVar~diff:551538
https://wiki.facepunch.com/gmod/Global.CreateConVar~diff:551581

**Comment by EntranceJew** [comment]
after i posted about it, rubat changed the default style of empty arguments
