### ISSUE TITLE
`include` and `IncludeCS` should not be treated as `require`

### ISSUE THREAD

**Issue by b0mbie** [luttje/glua-api-snippets#32]
This is how the [page for `include`](https://wiki.facepunch.com/gmod/Global.include) describes its first argument, `fileName`:
> The name of the script to be executed. The path must be either relative to the current file, or be an absolute path (relative to and excluding the `lua/` folder).

This argument is a path, which does not follow the `require` path format, where dots are separators.
If `include` is treated like Lua 5.1's [`dofile`](https://www.lua.org/manual/5.1/manual.html#pdf-dofile), it would be correct in this case.

**Comment by luttje** [comment]
Hi there, thanks for the clearly written issue, much appreciated 👍

For my own reference:
- https://github.com/luttje/glua-api-snippets/blob/ecf44405c2e5412801ec159541d55c6fa2159ae9/src/cli-library-publisher.ts#L64
- the LuaLS docs only mention require, but hopefully it works much like an alias: https://luals.github.io/wiki/settings/#runtimespecial

**Comment by luttje** [comment]
@all-contributors add @b0mbie for bug
