### ISSUE TITLE
`CSEnt` should inherit from `Entity`

### ISSUE THREAD

**Issue by b0mbie** [luttje/glua-api-snippets#36]
The [page for `CSEnt`](https://wiki.facepunch.com/gmod/CSEnt) states:
> Its base class is [`Entity`](https://wiki.facepunch.com/gmod/Entity) so it inherits all of the client and shared functions used by `Entity`.

Currently, `CSEnt` only has a single `CSEnt:Remove()` method.

**Comment by luttje** [comment]
Nice job on the contributions @b0mbie, much appreciated!

I don't have time to pick this up this month, so I'll leave some instructions here for if you (or anyone else) if you're feeling much more generous:
* To override how classes are inherited, we can override them in the [`custom/`](https://github.com/luttje/glua-api-snippets/tree/main/custom) directory.
* An example can be found in: https://github.com/luttje/glua-api-snippets/blob/main/custom/class.SWEP.lua
* I believe that for CSEnt a file named `class.CSEnt.lua` with contents similar to this should work:
```lua
---@class CSEnt : Entity
local CSEnt = {}
```
