### ISSUE TITLE
unsupported goto labels

### ISSUE THREAD

**Issue by Techbot121** [luttje/glua-api-snippets#54]
currently goto labels are being flagged for being incompatible, but they do indeed work since gmod is shipped with a embedded luajit library 

![image](https://github.com/luttje/glua-api-snippets/assets/3000604/92b2c763-231c-4065-80a0-67abea3001d8)

changing the `Lua.runtime.version` in the settings.json to `LuaJIT` fixes this. I don't think it should introduce some weird behaviour with LLS but I didn't know what to test for.

**Comment by luttje** [comment]
Thanks for reporting!

Since Garry's Mod uses LuaJIT I think setting that as the runtime version should be fine. If you notice no problems in your projects with it, feel free to make a PR and I'll merge it.

Thanks

**Comment by luttje** [comment]
@all-contributors please add @Techbot121 for bug
